-- PATCH FOR MEDIA TABLE TO MATCH API EXPECTATIONS
ALTER TABLE public.media RENAME COLUMN file_name TO filename;
ALTER TABLE public.media ADD COLUMN IF NOT EXISTS original_name TEXT;
ALTER TABLE public.media ADD COLUMN IF NOT EXISTS uploaded_by TEXT;
