export const SEED_DATA = {
  site_config: [
    { key: 'site_name', value: 'QUANTIFYRE LLP' },
    { key: 'tagline', value: 'The Future, Faster' },
    { key: 'llpin', value: 'ACG-0636' },
    { key: 'logo_header', value: '/logo.png' },
    { key: 'logo_footer', value: '/logo-footer.png' },
    { key: 'meta_title', value: 'QUANTIFYRE LLP — The Future, Faster' },
    { key: 'meta_description', value: 'AI-Powered Digital Transformation & Software Engineering Firm. We build AI-powered software for high-growth enterprises.' },
    { key: 'email', value: 'Info.endlessinfosys@gmail.com' },
    { key: 'phone_primary', value: '+91 6356195625' },
    { key: 'phone_alternate', value: '+91 7778095625' },
    { key: 'address_full', value: 'B-402, The Landmark, Opp. Kansar Hotel, Kudasan, Gandhinagar, Gujarat 382421' },
    { key: 'address_short', value: 'Kudasan, Gandhinagar, Gujarat' },
    { key: 'linkedin_url', value: 'https://linkedin.com/in/tishypatelofficial' },
    { key: 'instagram_url', value: 'https://instagram.com/quantifyre_llp_official' },
    { key: 'twitter_url', value: '#' },
    { key: 'sister_brand_url', value: 'https://endlessinfosys.com' },
    { key: 'copyright_text', value: '© 2025 QUANTIFYRE LLP (LLPIN: ACG-0636). All Rights Reserved.' },
    { key: 'footer_tagline', value: 'The Future, Faster.' },
    { key: 'footer_description', value: 'AI-Powered Digital Transformation & Software Engineering Firm helping high-growth enterprises scale faster.' },
    { key: 'international_presence', value: '🇦🇪 Dubai | 🇬🇧 London | 🇨🇦 Canada | 🇦🇺 Australia' },
    { key: 'loading_bar_text', value: 'Initializing AI Core…' },
    { key: 'loading_bar_sub', value: 'LLPIN: ACG-0636 · Gandhinagar, India' },
    { key: 'google_analytics_id', value: '' },
  ],
  nav_items: [
    { label: 'Home', href: '/', order_index: 0 },
    { label: 'About Us', href: '/about', order_index: 1 },
    { label: 'Services', href: '/services', order_index: 2 },
    { label: 'Portfolio', href: '/portfolio', order_index: 3 },
    { label: 'Blogs', href: '/blog', order_index: 4 },
    { label: 'Contact Us', href: '/contact', order_index: 5 },
    { label: "Let's Talk", href: '/contact', order_index: 6, is_cta: true },
  ],
  hero_sections: [
    {
      page: 'home',
      badge_text: 'Enterprise IT Engineering',
      heading_line1: 'Build High-Performance',
      heading_highlight: 'Software',
      heading_line2: '.',
      subtext: 'We are a technology agency building scalable web applications, enterprise ERPs, and AI-driven automation systems for modern businesses.',
      cta1_label: 'Start a Project',
      cta1_link: '/contact',
      cta2_label: 'View Capabilities',
      cta2_link: '/portfolio',
      extra_json: {
        trust_text: '50+ Businesses Trust Us',
        badges: [
          { label: 'quantifyre-admin.production', type: 'status' },
          { label: 'System Architecture', type: 'system' },
          { label: 'Next.js 14 • Node.js • PostgreSQL', type: 'tech' },
          { label: 'UI Component', type: 'ui' },
          { label: 'Compiled successfully', type: 'compiled' },
        ],
      },
    },
    {
      page: 'about',
      badge_text: 'About QUANTIFYRE LLP',
      heading_line1: 'Builders of',
      heading_highlight: 'Digital Empires',
      heading_line2: '.',
      subtext: 'QUANTIFYRE LLP (LLPIN: ACG-0636) is a registered IT engineering firm based in Gandhinagar, India — building AI-powered digital infrastructure for ambitious businesses globally.',
      cta1_label: 'Work With Us',
      cta1_link: '/contact',
      cta2_label: 'Our Services',
      cta2_link: '/services',
    },
    {
      page: 'services',
      badge_text: 'Service Architecture Index',
      heading_line1: 'Enterprise',
      heading_highlight: 'Capabilities',
      heading_line2: '.',
      subtext: 'Explore our strict, scalable, and highly available engineering services. Built for organizations that demand precision.',
    },
  ],
  services: [
    {
      slug: 'ai-automation',
      title: 'AI Automation & Solutions',
      description: 'We design intelligent automation that eliminates manual work and scales your operations.',
      icon: '🤖',
      tags: ['Python', 'OpenAI', 'LangChain', '+1'],
      detail_page_badge: 'Service: AI Automation',
      detail_page_h1: 'Work Smarter, Not Harder.',
      detail_page_subtext: 'Let machines do the heavy lifting — so your team focuses on what humans do best. We build custom AI agents that automate your entire workflow.',
      detail_page_stats: [
        { value: '10x', label: 'Faster Operations' },
        { value: '99.9%', label: 'Accuracy Rate' },
        { value: '24/7', label: 'Always Running' },
      ],
      detail_page_capabilities: [
        { title: 'Custom AI Agents', description: 'Purpose-built agents trained on your business data that automate entire workflows end-to-end.' },
        { title: 'LLM Integration', description: 'Connect GPT-4, Claude 3, and Gemini to your existing tools with secure, production-ready pipelines.' },
        { title: 'Predictive Analytics', description: 'ML models that forecast demand, detect anomalies, and surface actionable business insights.' },
        { title: 'RPA + AI Hybrid', description: 'Combine Robotic Process Automation with AI decision-making for legacy system compatibility.' },
      ],
      detail_page_deliverables: ['Custom AI Agents', 'Workflow Automation', 'Predictive Analytics', 'LLM Integration (GPT, Claude)'],
      detail_page_roadmap: ['Process Audit', 'Blueprint Design', 'Model Training', 'Integration', 'Monitoring'],
      order_index: 0,
    },
    {
      slug: 'software-engineering',
      title: 'Custom Software Engineering',
      description: 'Bespoke web apps, ERPs, CRMs, and platforms built for your exact business logic.',
      icon: '⚙️',
      tags: ['.NET', 'Node.js', 'Django', '+1'],
      order_index: 1,
    },
    {
      slug: 'web-development',
      title: 'Website Design & Development',
      description: 'High-performance, SEO-optimized websites built with Next.js for speed and conversion.',
      icon: '💻',
      tags: ['Next.js', 'TypeScript', 'TailwindCSS', '+1'],
      detail_page_badge: 'Web Dev',
      detail_page_h1: 'Pixel Perfect.',
      detail_page_subtext: 'Your website is your hardest-working sales rep. We build lightning-fast Next.js experiences that convert.',
      detail_page_stats: [
        { value: '<1s', label: 'Load Time' },
        { value: '100', label: 'Lighthouse Score' },
        { value: '2-4', label: 'Weeks Delivery' },
      ],
      order_index: 2,
    },
    {
      slug: 'digital-marketing',
      title: 'Digital Marketing Strategy',
      description: 'Data-driven campaigns, SEO, social media, and content that generates measurable ROI.',
      icon: '📈',
      tags: ['Google Analytics', 'SEMrush', 'Meta Ads', '+1'],
      order_index: 3,
    },
    {
      slug: 'mobile-development',
      title: 'Mobile App Development',
      description: 'Cross-platform Flutter and React Native apps that work beautifully on every device.',
      icon: '📱',
      tags: ['Flutter', 'React Native', 'Swift', '+1'],
      order_index: 4,
    },
    {
      slug: 'uiux-design',
      title: 'UI/UX Design',
      description: 'Research-driven design that converts — wireframes, prototypes, and pixel-perfect interfaces.',
      icon: '🎨',
      tags: ['Figma', 'Adobe XD', 'Protopie', '+1'],
      order_index: 5,
    },
  ],
  process_steps: [
    { step_number: 1, title: 'Discovery & Strategy', description: 'We understand your goals, audience, and technical requirements.', icon: '🔍' },
    { step_number: 2, title: 'UI/UX Design', description: 'Wireframes and interactive prototypes — your feedback shapes every pixel.', icon: '🎨' },
    { step_number: 3, title: 'Development', description: 'Clean, scalable code using the best-fit tech stack for your project.', icon: '💻' },
    { step_number: 4, title: 'Testing & QA', description: 'Rigorous testing across devices, browsers, and performance benchmarks.', icon: '🧪' },
    { step_number: 5, title: 'Launch', description: 'Smooth deployment with zero-downtime and full post-launch monitoring.', icon: '🚀' },
    { step_number: 6, title: 'Support & Scale', description: 'Ongoing maintenance, updates, and feature additions as you grow.', icon: '📈' },
  ],
  why_choose_us: [
    { title: 'AI-First Approach', description: 'Every solution we build has AI at its core — automation, intelligence, and speed.', icon: '🤖' },
    { title: 'Enterprise-Grade Quality', description: 'We build like a large agency but move like a startup — best of both worlds.', icon: '🏢' },
    { title: 'On-Time Delivery', description: 'Strict timelines, transparent communication, zero surprise delays.', icon: '⏱️' },
    { title: 'Full-Cycle Team', description: 'Design → Development → Testing → Launch → Support — one team, one invoice.', icon: '🔄' },
    { title: 'International Experience', description: 'Serving clients across India, Dubai, UK, Canada, and Australia.', icon: '🌐' },
    { title: 'Registered LLP', description: 'QUANTIFYRE LLP (LLPIN: ACG-0636) — fully registered, legally compliant.', icon: '⚖️' },
  ],
  about_stats: [
    { value: '12+', label: 'Projects Delivered' },
    { value: '8+', label: 'Happy Clients' },
    { value: '2+', label: 'Industries Served' },
    { value: '1', label: 'Year of Innovation' },
  ],
  about_mission_vision: [
    {
      type: 'mission',
      icon: '🎯',
      label: 'Our Mission',
      heading: 'Accelerate Ambition',
      body: 'To democratize access to enterprise-grade technology. We build intelligent systems that let every business — from a Gandhinagar startup to a Dubai-based enterprise — compete at the highest level.',
    },
    {
      type: 'vision',
      icon: '🔭',
      label: 'Our Vision',
      heading: 'The Future, Faster',
      body: 'A world where every business decision is powered by intelligent data, every operation is automated, and every product experience is pixel-perfect. We are engineering that world — one deployment at a time.',
    },
  ],
  faqs: [
    { question: 'What services does QUANTIFYRE offer?', answer: 'We offer AI automation, custom software engineering, website design and development, mobile app development, UI/UX design, digital marketing strategy, and enterprise ERP solutions.' },
    { question: 'How long does a typical project take?', answer: 'Project timelines vary based on complexity, but typical websites take 2-4 weeks, while complex ERP/AI systems can take 8-12 weeks.' },
    { question: 'Do you serve international clients?', answer: 'Yes, we have a strong presence in Dubai, UK, Canada, and Australia, serving clients globally with seamless remote collaboration.' },
    { question: 'What is your pricing model?', answer: 'We offer flexible pricing models including fixed-price projects, monthly retainers, and dedicated team modules based on project requirements.' },
    { question: 'Do you provide post-launch support?', answer: 'Absolutely. We provide comprehensive support, maintenance, and scaling services to ensure your systems remain performant and up-to-date.' },
    { question: 'What makes QUANTIFYRE different from other agencies?', answer: 'Our AI-first approach, enterprise-grade engineering standards, and commitment to transparent, on-time delivery set us apart.' },
    { question: 'Can you redesign an existing website?', answer: 'Yes, we specialize in high-performance redesigns, migrating legacy systems to modern stacks like Next.js for better speed and SEO.' },
    { question: 'How do I start a project?', answer: "Simply reach out via our contact form or email, and we'll schedule a free strategy call to discuss your project blueprint." },
  ],
  testimonials: [
    {
      quote: 'QUANTIFYRE transformed our operations with a custom ERP that actually works. Delivered on time, zero bugs.',
      author_name: 'Rajesh M.',
      author_role: 'Director',
      author_company: 'Education Sector',
      avatar_initial: 'R',
    },
    {
      quote: 'Their AI automation saved us 30+ hours per week. Genuinely impressed by the depth of their technical knowledge.',
      author_name: 'Priya S.',
      author_role: 'Founder',
      author_company: 'HealthTech Startup',
      avatar_initial: 'P',
    },
    {
      quote: 'Professional, responsive, and brilliant designers. Our website traffic doubled in 2 months.',
      author_name: 'Harshil C.',
      author_role: 'CEO',
      author_company: 'Luxelivein Furnishings',
      avatar_initial: 'H',
    },
  ],
  tech_stack: [
    { name: 'React', category: 'Frontend' },
    { name: 'Next.js', category: 'Frontend' },
    { name: 'Vue', category: 'Frontend' },
    { name: 'Angular', category: 'Frontend' },
    { name: 'TypeScript', category: 'Frontend' },
    { name: 'TailwindCSS', category: 'Frontend' },
    { name: 'Framer Motion', category: 'Frontend' },
    { name: 'Node.js', category: 'Backend' },
    { name: 'Python', category: 'Backend' },
    { name: 'Django', category: 'Backend' },
    { name: '.NET', category: 'Backend' },
    { name: 'PHP', category: 'Backend' },
    { name: 'Laravel', category: 'Backend' },
    { name: 'Spring Boot', category: 'Backend' },
    { name: 'OpenAI API', category: 'AI_ML' },
    { name: 'LangChain', category: 'AI_ML' },
    { name: 'TensorFlow', category: 'AI_ML' },
    { name: 'HuggingFace', category: 'AI_ML' },
    { name: 'Pinecone', category: 'AI_ML' },
    { name: 'Flutter', category: 'Mobile' },
    { name: 'React Native', category: 'Mobile' },
    { name: 'Swift', category: 'Mobile' },
    { name: 'Kotlin', category: 'Mobile' },
    { name: 'SQL Server', category: 'Database' },
    { name: 'PostgreSQL', category: 'Database' },
    { name: 'MySQL', category: 'Database' },
    { name: 'MongoDB', category: 'Database' },
    { name: 'Supabase', category: 'Database' },
    { name: 'Firebase', category: 'Database' },
    { name: 'AWS', category: 'Cloud' },
    { name: 'Azure', category: 'Cloud' },
    { name: 'GCP', category: 'Cloud' },
  ],
  portfolio_projects: [
    {
      title: 'School ERP System',
      slug: 'school-erp',
      category: 'Education',
      description: 'Multi-school management platform with RBAC, ADO.NET, SQL Server TDE',
      technologies: ['.NET', 'SQL Server', 'React'],
      is_featured: true,
    },
    {
      title: 'QUANTIFYRE IRIS',
      slug: 'quantifyre-iris',
      category: 'Marketing',
      description: 'AI agency management dashboard with campaign, lead, and budget tracking',
      technologies: ['Next.js', 'OpenAI', 'Supabase'],
      is_featured: true,
    },
    {
      title: 'Revive Motors',
      slug: 'revive-motors',
      category: 'Automotive',
      description: 'Django-based automotive management platform',
      technologies: ['Django', 'Python', 'PostgreSQL'],
      is_featured: true,
    },
  ],
  blog_posts: [
    {
      title: 'How AI Automation is Transforming Indian SMBs in 2025',
      slug: 'ai-automation-indian-smbs',
      excerpt: 'Discover how intelligent agents are helping small businesses compete with giants.',
      content: 'Full article content here...',
      category: 'AI Automation',
      read_time: '5 min read',
      is_published: true,
      show_on_home: true,
    },
    {
      title: 'Why Your Next Website Should Be Built With Next.js 14',
      slug: 'why-nextjs-14',
      excerpt: 'Speed, SEO, and developer experience — why Next.js is the industry standard.',
      content: 'Full article content here...',
      category: 'Web Development',
      read_time: '4 min read',
      is_published: true,
      show_on_home: true,
    },
    {
      title: 'The Enterprise Admin Panel Architecture Every SaaS Needs',
      slug: 'enterprise-admin-panel-architecture',
      excerpt: 'Best practices for building scalable and secure administrative interfaces.',
      content: 'Full article content here...',
      category: 'Software Engineering',
      read_time: '6 min read',
      is_published: true,
      show_on_home: true,
    },
  ],
  cta_sections: [
    {
      page: 'global',
      section_label: 'Unlimited Potential',
      heading: "Let's Engineer Your Digital Legacy.",
      subtext: 'The future waits for no one. Partner with QUANTIFYRE to build intelligent systems that scale with your ambition.',
      btn1_label: '🚀Start the Mission',
      btn1_link: '/contact',
      btn2_label: 'Free Strategy Call 📞',
      btn2_link: '/contact',
    },
  ],
  sister_brand: [
    {
      section_label: 'Sister Brand',
      heading: 'Meet ENDLESSINFOSYS.',
      brand_name: 'ENDLESSINFOSYS',
      description: 'Our elite digital agency brand specialized in high-performance graphic design, social media growth, and full-spectrum digital marketing.',
      cta_label: 'Go Beyond',
      cta_link: 'https://endlessinfosys.com',
    },
  ],
  contact_form_config: [
    {
      form_heading: 'New Project Request',
      submit_btn_label: '🚀Launch Your Project',
      trust_text: '🔒 End-to-end encrypted · No spam, ever · NDA available on request',
      success_message: "Thank you! We've received your request and will get back to you within 24 hours.",
      notification_email: 'Info.endlessinfosys@gmail.com',
    },
  ],
  contact_form_fields: [
    { field_key: 'full_name', label: '👤Full Name *', placeholder: 'Enter your name', field_type: 'text', is_required: true, order_index: 0 },
    { field_key: 'email', label: '✉️Email Address *', placeholder: 'Enter your email', field_type: 'email', is_required: true, order_index: 1 },
    { field_key: 'phone', label: '📱Phone Number', placeholder: '+91', field_type: 'phone', is_required: false, order_index: 2 },
    {
      field_key: 'services',
      label: '🛠️ Services Interested In',
      field_type: 'checkbox_group',
      options: [
        { label: 'AI Automation & Solutions', value: 'ai-automation' },
        { label: 'Custom Software Engineering', value: 'software-engineering' },
        { label: 'Website Design & Development', value: 'web-development' },
        { label: 'Digital Marketing Strategy', value: 'digital-marketing' },
        { label: 'Mobile App Development', value: 'mobile-development' },
        { label: 'UI/UX Design', value: 'uiux-design' },
      ],
      order_index: 3,
    },
    { field_key: 'project_details', label: '💬Project Details *', placeholder: 'Tell us about your project', field_type: 'textarea', is_required: true, max_length: 300, order_index: 4 },
  ],
};
